In [2]:
import numpy as np
import pandas as pd
import joblib
import os

from scipy.stats import randint
from sklearn.metrics import classification_report

from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV

from config import SEED

Elegimos dataset

In [3]:
dataset = 'crudos'

## Espectrogramas

Se suelen usar Mel espectrogramas

In [3]:
train_data = np.load(f'./dataset/ventanas_procesadas/{dataset}/train_melspectrogram.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/ventanas_procesadas/{dataset}/test_melspectrogram.npz')
X_test = test_data['X']
y_test = test_data['y']

In [4]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((3993, 64128), (3993,), (999, 64128), (999,))

### Random Forest

#### Entrenamiento

In [7]:
rf = RandomForestClassifier(random_state=SEED, n_jobs=-1, max_features='sqrt')
param_distributions = {
    'max_depth': [10, 15, 20, 25],
    'min_samples_split': [10, 20, 30],
    'min_samples_leaf': [5, 10 , 15]
}

In [9]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=20,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END max_depth=25, min_samples_leaf=15, min_samples_split=30;, score=0.670 total time=  12.3s
[CV 2/5] END max_depth=25, min_samples_leaf=15, min_samples_split=30;, score=0.668 total time=  15.1s
[CV 3/5] END max_depth=25, min_samples_leaf=15, min_samples_split=30;, score=0.691 total time=  14.5s
[CV 4/5] END max_depth=25, min_samples_leaf=15, min_samples_split=30;, score=0.657 total time=  14.3s
[CV 5/5] END max_depth=25, min_samples_leaf=15, min_samples_split=30;, score=0.711 total time=  14.1s
[CV 1/5] END max_depth=15, min_samples_leaf=10, min_samples_split=20;, score=0.679 total time=  17.7s
[CV 2/5] END max_depth=15, min_samples_leaf=10, min_samples_split=20;, score=0.676 total time=  24.8s
[CV 3/5] END max_depth=15, min_samples_leaf=10, min_samples_split=20;, score=0.703 total time=  16.3s
[CV 4/5] END max_depth=15, min_samples_leaf=10, min_samples_split=20;, score=0.657 total time=  25.5s
[CV 5/5] END max_depth=15, min_samples_leaf=10, min_samples_split=20;, score=0.705 total time=  26.1s
[CV 1/5] END max_depth=20, min_samples_leaf=15, min_samples_split=30;, score=0.671 total time=  23.6s
[CV 2/5] END max_depth=20, min_samples_leaf=15, min_samples_split=30;, score=0.668 total time=  21.9s
[CV 3/5] END max_depth=20, min_samples_leaf=15, min_samples_split=30;, score=0.690 total time=  11.1s
[CV 4/5] END max_depth=20, min_samples_leaf=15, min_samples_split=30;, score=0.658 total time=  11.2s
[CV 5/5] END max_depth=20, min_samples_leaf=15, min_samples_split=30;, score=0.711 total time=  13.8s
[CV 1/5] END max_depth=25, min_samples_leaf=10, min_samples_split=10;, score=0.682 total time=  18.1s
[CV 2/5] END max_depth=25, min_samples_leaf=10, min_samples_split=10;, score=0.684 total time=  25.6s
[CV 3/5] END max_depth=25, min_samples_leaf=10, min_samples_split=10;, score=0.711 total time=  25.3s
[CV 4/5] END max_depth=25, min_samples_leaf=10, min_samples_split=10;, score=0.652 total time=  25.9s
[CV 5/5] END max_depth=25, min_samples_leaf=10, min_samples_split=10;, score=0.699 total time=  25.9s
[CV 1/5] END max_depth=15, min_samples_leaf=15, min_samples_split=20;, score=0.672 total time=  24.1s
[CV 2/5] END max_depth=15, min_samples_leaf=15, min_samples_split=20;, score=0.664 total time=  15.8s
[CV 3/5] END max_depth=15, min_samples_leaf=15, min_samples_split=20;, score=0.689 total time=  19.9s
[CV 4/5] END max_depth=15, min_samples_leaf=15, min_samples_split=20;, score=0.657 total time=  19.8s
[CV 5/5] END max_depth=15, min_samples_leaf=15, min_samples_split=20;, score=0.714 total time=  23.7s
[CV 1/5] END max_depth=25, min_samples_leaf=10, min_samples_split=20;, score=0.682 total time=  26.7s
[CV 2/5] END max_depth=25, min_samples_leaf=10, min_samples_split=20;, score=0.684 total time=  27.2s
[CV 3/5] END max_depth=25, min_samples_leaf=10, min_samples_split=20;, score=0.711 total time=  25.4s
[CV 4/5] END max_depth=25, min_samples_leaf=10, min_samples_split=20;, score=0.652 total time=  25.8s
[CV 5/5] END max_depth=25, min_samples_leaf=10, min_samples_split=20;, score=0.699 total time=  25.8s
[CV 1/5] END max_depth=20, min_samples_leaf=10, min_samples_split=10;, score=0.681 total time=  26.4s
[CV 2/5] END max_depth=20, min_samples_leaf=10, min_samples_split=10;, score=0.683 total time=  26.5s
[CV 3/5] END max_depth=20, min_samples_leaf=10, min_samples_split=10;, score=0.711 total time=  25.8s
[CV 4/5] END max_depth=20, min_samples_leaf=10, min_samples_split=10;, score=0.654 total time=  26.2s
[CV 5/5] END max_depth=20, min_samples_leaf=10, min_samples_split=10;, score=0.697 total time=  25.7s
[CV 1/5] END max_depth=15, min_samples_leaf=10, min_samples_split=10;, score=0.679 total time=  25.4s
[CV 2/5] END max_depth=15, min_samples_leaf=10, min_samples_split=10;, score=0.676 total time=  25.4s
[CV 3/5] END max_depth=15, min_samples_leaf=10, min_samples_split=10;, score=0.703 total time=  25.2s
[CV 4/5] END max_depth=15, min_samples_leaf=10, min_samples_split=10;, score=0.657 total time=  25.9s
[CV 5/5] END max_depth=15, min_samples_leaf=10, min_samples_split=10;, score=0.705 total time=  25.2s
[CV 1/5] END max_depth=10, min_samples_leaf=15, min_samples_split=30;, score=0.667 total time=  21.2s
[CV 2/5] END max_depth=10, min_samples_leaf=15, min_samples_split=30;, score=0.666 total time=  17.4s
[CV 3/5] END max_depth=10, min_samples_leaf=15, min_samples_split=30;, score=0.688 total time=  20.9s
[CV 4/5] END max_depth=10, min_samples_leaf=15, min_samples_split=30;, score=0.657 total time=  21.1s
[CV 5/5] END max_depth=10, min_samples_leaf=15, min_samples_split=30;, score=0.709 total time=  21.6s
[CV 1/5] END max_depth=15, min_samples_leaf=15, min_samples_split=30;, score=0.672 total time=  23.6s
[CV 2/5] END max_depth=15, min_samples_leaf=15, min_samples_split=30;, score=0.664 total time=  24.3s
[CV 3/5] END max_depth=15, min_samples_leaf=15, min_samples_split=30;, score=0.689 total time=  23.4s
[CV 4/5] END max_depth=15, min_samples_leaf=15, min_samples_split=30;, score=0.657 total time=  23.7s
[CV 5/5] END max_depth=15, min_samples_leaf=15, min_samples_split=30;, score=0.714 total time=  23.1s
[CV 1/5] END max_depth=15, min_samples_leaf=5, min_samples_split=10;, score=0.681 total time=  26.9s
[CV 2/5] END max_depth=15, min_samples_leaf=5, min_samples_split=10;, score=0.672 total time=  27.1s
[CV 3/5] END max_depth=15, min_samples_leaf=5, min_samples_split=10;, score=0.699 total time=  26.7s
[CV 4/5] END max_depth=15, min_samples_leaf=5, min_samples_split=10;, score=0.668 total time=  26.6s
[CV 5/5] END max_depth=15, min_samples_leaf=5, min_samples_split=10;, score=0.709 total time=  26.9s
[CV 1/5] END max_depth=25, min_samples_leaf=15, min_samples_split=20;, score=0.670 total time=  23.3s
[CV 2/5] END max_depth=25, min_samples_leaf=15, min_samples_split=20;, score=0.668 total time=  23.7s
[CV 3/5] END max_depth=25, min_samples_leaf=15, min_samples_split=20;, score=0.691 total time=  23.6s
[CV 4/5] END max_depth=25, min_samples_leaf=15, min_samples_split=20;, score=0.657 total time=  24.0s
[CV 5/5] END max_depth=25, min_samples_leaf=15, min_samples_split=20;, score=0.711 total time=  20.4s
[CV 1/5] END max_depth=10, min_samples_leaf=5, min_samples_split=10;, score=0.667 total time=  16.7s
[CV 2/5] END max_depth=10, min_samples_leaf=5, min_samples_split=10;, score=0.666 total time=  23.5s
[CV 3/5] END max_depth=10, min_samples_leaf=5, min_samples_split=10;, score=0.686 total time=  23.4s
[CV 4/5] END max_depth=10, min_samples_leaf=5, min_samples_split=10;, score=0.658 total time=  22.9s
[CV 5/5] END max_depth=10, min_samples_leaf=5, min_samples_split=10;, score=0.707 total time=  23.3s
[CV 1/5] END max_depth=10, min_samples_leaf=10, min_samples_split=20;, score=0.675 total time=  22.4s
[CV 2/5] END max_depth=10, min_samples_leaf=10, min_samples_split=20;, score=0.662 total time=  22.3s
[CV 3/5] END max_depth=10, min_samples_leaf=10, min_samples_split=20;, score=0.689 total time=  22.3s
[CV 4/5] END max_depth=10, min_samples_leaf=10, min_samples_split=20;, score=0.657 total time=  22.2s
[CV 5/5] END max_depth=10, min_samples_leaf=10, min_samples_split=20;, score=0.701 total time=  22.2s
[CV 1/5] END max_depth=25, min_samples_leaf=5, min_samples_split=30;, score=0.678 total time=  27.7s
[CV 2/5] END max_depth=25, min_samples_leaf=5, min_samples_split=30;, score=0.668 total time=  27.7s
[CV 3/5] END max_depth=25, min_samples_leaf=5, min_samples_split=30;, score=0.696 total time=  26.6s
[CV 4/5] END max_depth=25, min_samples_leaf=5, min_samples_split=30;, score=0.656 total time=  27.6s
[CV 5/5] END max_depth=25, min_samples_leaf=5, min_samples_split=30;, score=0.699 total time=  27.5s
[CV 1/5] END max_depth=15, min_samples_leaf=15, min_samples_split=10;, score=0.672 total time=  23.5s
[CV 2/5] END max_depth=15, min_samples_leaf=15, min_samples_split=10;, score=0.664 total time=  23.3s
[CV 3/5] END max_depth=15, min_samples_leaf=15, min_samples_split=10;, score=0.689 total time=  23.3s
[CV 4/5] END max_depth=15, min_samples_leaf=15, min_samples_split=10;, score=0.657 total time=  24.0s
[CV 5/5] END max_depth=15, min_samples_leaf=15, min_samples_split=10;, score=0.714 total time=  23.5s
[CV 1/5] END max_depth=20, min_samples_leaf=5, min_samples_split=20;, score=0.670 total time=  27.4s
[CV 2/5] END max_depth=20, min_samples_leaf=5, min_samples_split=20;, score=0.663 total time=  23.8s
[CV 3/5] END max_depth=20, min_samples_leaf=5, min_samples_split=20;, score=0.700 total time=  26.8s
[CV 4/5] END max_depth=20, min_samples_leaf=5, min_samples_split=20;, score=0.662 total time=  27.4s
[CV 5/5] END max_depth=20, min_samples_leaf=5, min_samples_split=20;, score=0.721 total time=  14.6s
[CV 1/5] END max_depth=10, min_samples_leaf=10, min_samples_split=30;, score=0.668 total time=  21.2s
[CV 2/5] END max_depth=10, min_samples_leaf=10, min_samples_split=30;, score=0.672 total time=  22.0s
[CV 3/5] END max_depth=10, min_samples_leaf=10, min_samples_split=30;, score=0.696 total time=  11.7s
[CV 4/5] END max_depth=10, min_samples_leaf=10, min_samples_split=30;, score=0.655 total time=  20.4s
[CV 5/5] END max_depth=10, min_samples_leaf=10, min_samples_split=30;, score=0.699 total time=  21.9s
[CV 1/5] END max_depth=15, min_samples_leaf=5, min_samples_split=30;, score=0.674 total time=  25.6s
[CV 2/5] END max_depth=15, min_samples_leaf=5, min_samples_split=30;, score=0.671 total time=  26.2s
[CV 3/5] END max_depth=15, min_samples_leaf=5, min_samples_split=30;, score=0.695 total time=  26.0s
[CV 4/5] END max_depth=15, min_samples_leaf=5, min_samples_split=30;, score=0.654 total time=  26.6s
[CV 5/5] END max_depth=15, min_samples_leaf=5, min_samples_split=30;, score=0.700 total time=  26.4s
[CV 1/5] END max_depth=10, min_samples_leaf=5, min_samples_split=20;, score=0.668 total time=  18.3s
[CV 2/5] END max_depth=10, min_samples_leaf=5, min_samples_split=20;, score=0.671 total time=  18.6s
[CV 3/5] END max_depth=10, min_samples_leaf=5, min_samples_split=20;, score=0.695 total time=  22.8s
[CV 4/5] END max_depth=10, min_samples_leaf=5, min_samples_split=20;, score=0.651 total time=  18.9s
[CV 5/5] END max_depth=10, min_samples_leaf=5, min_samples_split=20;, score=0.706 total time=  23.4s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
                   n_iter=20,
                   param_distributions={'max_depth': [10, 15, 20, 25],
                                        'min_samples_leaf': [5, 10, 15],
                                        'min_samples_split': [10, 20, 30]},
                   random_state=42, scoring='roc_auc', verbose=3)

In [10]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False).head(10)

    param_max_depth  ...  mean_test_score
10               15  ...         0.685927
3                25  ...         0.685656
5                25  ...         0.685656
6                20  ...         0.685176
1                15  ...         0.684012
7                15  ...         0.684012
16               20  ...         0.683231
2                20  ...         0.679507
0                25  ...         0.679424
11               25  ...         0.679424

[10 rows x 4 columns]

In [11]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'min_samples_split': 10, 'min_samples_leaf': 5, 'max_depth': 15}
Best CV score: 0.6859267138539586

In [12]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      1933
           1       0.99      1.00      0.99      2060

    accuracy                           0.99      3993
   macro avg       0.99      0.99      0.99      3993
weighted avg       0.99      0.99      0.99      3993

#### Evaluación

In [13]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.66      0.59      0.62       484
           1       0.65      0.71      0.68       515

    accuracy                           0.65       999
   macro avg       0.65      0.65      0.65       999
weighted avg       0.65      0.65      0.65       999

#### Guardado

In [14]:
os.makedirs(f'./modelos_clasicos/modelos/ventanas/{dataset}', exist_ok=True)

joblib.dump(best_model, f'./modelos_clasicos/modelos/ventanas/{dataset}/melspec_rf.pkl')

['./modelos_clasicos/modelos/ventanas/crudos/melspec_rf.pkl']

## Features de Audio

In [9]:
train_data = np.load(f'./dataset/ventanas_procesadas/{dataset}/train_features.npz')
X_train = train_data['X']
y_train = train_data['y']

test_data = np.load(f'./dataset/ventanas_procesadas/{dataset}/test_features.npz')
X_test = test_data['X']
y_test = test_data['y']

In [10]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((3993, 46), (3993,), (999, 46), (999,))

### Random Forest

#### Entrenamiento

In [ ]:
rf = RandomForestClassifier(random_state=SEED, n_jobs=-1, max_features=None)

param_distributions = {
    'max_depth': randint(10, 20),
    'min_samples_split': randint(15, 30),
    'min_samples_leaf': randint(5, 15)
}

In [6]:
rnd_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_distributions,
    n_iter=50,
    scoring='roc_auc',
    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED),
    verbose=3,
    random_state=SEED
)

rnd_search.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[CV 1/5] END max_depth=16, min_samples_leaf=8, min_samples_split=27;, score=0.819 total time=   1.5s
[CV 2/5] END max_depth=16, min_samples_leaf=8, min_samples_split=27;, score=0.836 total time=   1.6s
[CV 3/5] END max_depth=16, min_samples_leaf=8, min_samples_split=27;, score=0.840 total time=   1.6s
[CV 4/5] END max_depth=16, min_samples_leaf=8, min_samples_split=27;, score=0.850 total time=   1.5s
[CV 5/5] END max_depth=16, min_samples_leaf=8, min_samples_split=27;, score=0.832 total time=   1.7s
[CV 1/5] END max_depth=17, min_samples_leaf=9, min_samples_split=21;, score=0.826 total time=   2.4s
[CV 2/5] END max_depth=17, min_samples_leaf=9, min_samples_split=21;, score=0.835 total time=   2.6s
[CV 3/5] END max_depth=17, min_samples_leaf=9, min_samples_split=21;, score=0.842 total time=   2.4s
[CV 4/5] END max_depth=17, min_samples_leaf=9, min_samples_split=21;, score=0.856 total time=   2.5s
[CV 5/5] END max_depth=17, min_samples_leaf=9, min_samples_split=21;, score=0.837 total time=   2.4s
[CV 1/5] END max_depth=19, min_samples_leaf=7, min_samples_split=21;, score=0.825 total time=   2.5s
[CV 2/5] END max_depth=19, min_samples_leaf=7, min_samples_split=21;, score=0.842 total time=   2.5s
[CV 3/5] END max_depth=19, min_samples_leaf=7, min_samples_split=21;, score=0.848 total time=   2.3s
[CV 4/5] END max_depth=19, min_samples_leaf=7, min_samples_split=21;, score=0.856 total time=   2.3s
[CV 5/5] END max_depth=19, min_samples_leaf=7, min_samples_split=21;, score=0.836 total time=   2.4s
[CV 1/5] END max_depth=17, min_samples_leaf=9, min_samples_split=18;, score=0.828 total time=   2.2s
[CV 2/5] END max_depth=17, min_samples_leaf=9, min_samples_split=18;, score=0.840 total time=   2.3s
[CV 3/5] END max_depth=17, min_samples_leaf=9, min_samples_split=18;, score=0.845 total time=   2.3s
[CV 4/5] END max_depth=17, min_samples_leaf=9, min_samples_split=18;, score=0.858 total time=   2.4s
[CV 5/5] END max_depth=17, min_samples_leaf=9, min_samples_split=18;, score=0.840 total time=   2.3s
[CV 1/5] END max_depth=17, min_samples_leaf=12, min_samples_split=17;, score=0.816 total time=   2.1s
[CV 2/5] END max_depth=17, min_samples_leaf=12, min_samples_split=17;, score=0.834 total time=   2.4s
[CV 3/5] END max_depth=17, min_samples_leaf=12, min_samples_split=17;, score=0.832 total time=   2.1s
[CV 4/5] END max_depth=17, min_samples_leaf=12, min_samples_split=17;, score=0.848 total time=   2.4s
[CV 5/5] END max_depth=17, min_samples_leaf=12, min_samples_split=17;, score=0.829 total time=   2.3s
[CV 1/5] END max_depth=15, min_samples_leaf=9, min_samples_split=16;, score=0.828 total time=   2.6s
[CV 2/5] END max_depth=15, min_samples_leaf=9, min_samples_split=16;, score=0.839 total time=   3.0s
[CV 3/5] END max_depth=15, min_samples_leaf=9, min_samples_split=16;, score=0.844 total time=   2.7s
[CV 4/5] END max_depth=15, min_samples_leaf=9, min_samples_split=16;, score=0.857 total time=   3.6s
[CV 5/5] END max_depth=15, min_samples_leaf=9, min_samples_split=16;, score=0.840 total time=   4.1s
[CV 1/5] END max_depth=17, min_samples_leaf=10, min_samples_split=16;, score=0.826 total time=   3.8s
[CV 2/5] END max_depth=17, min_samples_leaf=10, min_samples_split=16;, score=0.839 total time=   3.9s
[CV 3/5] END max_depth=17, min_samples_leaf=10, min_samples_split=16;, score=0.839 total time=   3.4s
[CV 4/5] END max_depth=17, min_samples_leaf=10, min_samples_split=16;, score=0.853 total time=   3.8s
[CV 5/5] END max_depth=17, min_samples_leaf=10, min_samples_split=16;, score=0.837 total time=   4.2s
[CV 1/5] END max_depth=14, min_samples_leaf=5, min_samples_split=26;, score=0.822 total time=   3.3s
[CV 2/5] END max_depth=14, min_samples_leaf=5, min_samples_split=26;, score=0.843 total time=   3.5s
[CV 3/5] END max_depth=14, min_samples_leaf=5, min_samples_split=26;, score=0.846 total time=   3.6s
[CV 4/5] END max_depth=14, min_samples_leaf=5, min_samples_split=26;, score=0.853 total time=   2.6s
[CV 5/5] END max_depth=14, min_samples_leaf=5, min_samples_split=26;, score=0.836 total time=   2.4s
[CV 1/5] END max_depth=19, min_samples_leaf=10, min_samples_split=27;, score=0.818 total time=   2.3s
[CV 2/5] END max_depth=19, min_samples_leaf=10, min_samples_split=27;, score=0.833 total time=   2.4s
[CV 3/5] END max_depth=19, min_samples_leaf=10, min_samples_split=27;, score=0.834 total time=   2.2s
[CV 4/5] END max_depth=19, min_samples_leaf=10, min_samples_split=27;, score=0.848 total time=   2.3s
[CV 5/5] END max_depth=19, min_samples_leaf=10, min_samples_split=27;, score=0.831 total time=   2.3s
[CV 1/5] END max_depth=18, min_samples_leaf=5, min_samples_split=25;, score=0.824 total time=   2.5s
[CV 2/5] END max_depth=18, min_samples_leaf=5, min_samples_split=25;, score=0.846 total time=   2.5s
[CV 3/5] END max_depth=18, min_samples_leaf=5, min_samples_split=25;, score=0.848 total time=   2.5s
[CV 4/5] END max_depth=18, min_samples_leaf=5, min_samples_split=25;, score=0.856 total time=   2.6s
[CV 5/5] END max_depth=18, min_samples_leaf=5, min_samples_split=25;, score=0.838 total time=   2.5s
[CV 1/5] END max_depth=19, min_samples_leaf=7, min_samples_split=26;, score=0.820 total time=   2.4s
[CV 2/5] END max_depth=19, min_samples_leaf=7, min_samples_split=26;, score=0.839 total time=   2.5s
[CV 3/5] END max_depth=19, min_samples_leaf=7, min_samples_split=26;, score=0.843 total time=   2.3s
[CV 4/5] END max_depth=19, min_samples_leaf=7, min_samples_split=26;, score=0.852 total time=   2.5s
[CV 5/5] END max_depth=19, min_samples_leaf=7, min_samples_split=26;, score=0.831 total time=   2.7s
[CV 1/5] END max_depth=16, min_samples_leaf=8, min_samples_split=23;, score=0.823 total time=   2.7s
[CV 2/5] END max_depth=16, min_samples_leaf=8, min_samples_split=23;, score=0.839 total time=   2.8s
[CV 3/5] END max_depth=16, min_samples_leaf=8, min_samples_split=23;, score=0.842 total time=   2.5s
[CV 4/5] END max_depth=16, min_samples_leaf=8, min_samples_split=23;, score=0.855 total time=   2.5s
[CV 5/5] END max_depth=16, min_samples_leaf=8, min_samples_split=23;, score=0.834 total time=   2.4s
[CV 1/5] END max_depth=12, min_samples_leaf=9, min_samples_split=17;, score=0.825 total time=   2.3s
[CV 2/5] END max_depth=12, min_samples_leaf=9, min_samples_split=17;, score=0.834 total time=   2.4s
[CV 3/5] END max_depth=12, min_samples_leaf=9, min_samples_split=17;, score=0.842 total time=   2.3s
[CV 4/5] END max_depth=12, min_samples_leaf=9, min_samples_split=17;, score=0.853 total time=   2.3s
[CV 5/5] END max_depth=12, min_samples_leaf=9, min_samples_split=17;, score=0.835 total time=   2.3s
[CV 1/5] END max_depth=16, min_samples_leaf=9, min_samples_split=23;, score=0.823 total time=   2.3s
[CV 2/5] END max_depth=16, min_samples_leaf=9, min_samples_split=23;, score=0.833 total time=   2.4s
[CV 3/5] END max_depth=16, min_samples_leaf=9, min_samples_split=23;, score=0.840 total time=   2.8s
[CV 4/5] END max_depth=16, min_samples_leaf=9, min_samples_split=23;, score=0.854 total time=   2.8s
[CV 5/5] END max_depth=16, min_samples_leaf=9, min_samples_split=23;, score=0.835 total time=   2.7s
[CV 1/5] END max_depth=16, min_samples_leaf=6, min_samples_split=18;, score=0.831 total time=   2.8s
[CV 2/5] END max_depth=16, min_samples_leaf=6, min_samples_split=18;, score=0.847 total time=   2.9s
[CV 3/5] END max_depth=16, min_samples_leaf=6, min_samples_split=18;, score=0.852 total time=   2.7s
[CV 4/5] END max_depth=16, min_samples_leaf=6, min_samples_split=18;, score=0.858 total time=   2.6s
[CV 5/5] END max_depth=16, min_samples_leaf=6, min_samples_split=18;, score=0.841 total time=   2.5s
[CV 1/5] END max_depth=18, min_samples_leaf=6, min_samples_split=24;, score=0.825 total time=   2.5s
[CV 2/5] END max_depth=18, min_samples_leaf=6, min_samples_split=24;, score=0.842 total time=   2.5s
[CV 3/5] END max_depth=18, min_samples_leaf=6, min_samples_split=24;, score=0.847 total time=   2.5s
[CV 4/5] END max_depth=18, min_samples_leaf=6, min_samples_split=24;, score=0.855 total time=   2.5s
[CV 5/5] END max_depth=18, min_samples_leaf=6, min_samples_split=24;, score=0.835 total time=   2.5s
[CV 1/5] END max_depth=18, min_samples_leaf=14, min_samples_split=19;, score=0.813 total time=   2.1s
[CV 2/5] END max_depth=18, min_samples_leaf=14, min_samples_split=19;, score=0.828 total time=   2.2s
[CV 3/5] END max_depth=18, min_samples_leaf=14, min_samples_split=19;, score=0.827 total time=   2.1s
[CV 4/5] END max_depth=18, min_samples_leaf=14, min_samples_split=19;, score=0.842 total time=   2.2s
[CV 5/5] END max_depth=18, min_samples_leaf=14, min_samples_split=19;, score=0.825 total time=   2.2s
[CV 1/5] END max_depth=11, min_samples_leaf=8, min_samples_split=26;, score=0.814 total time=   2.2s
[CV 2/5] END max_depth=11, min_samples_leaf=8, min_samples_split=26;, score=0.829 total time=   2.5s
[CV 3/5] END max_depth=11, min_samples_leaf=8, min_samples_split=26;, score=0.835 total time=   2.6s
[CV 4/5] END max_depth=11, min_samples_leaf=8, min_samples_split=26;, score=0.843 total time=   2.7s
[CV 5/5] END max_depth=11, min_samples_leaf=8, min_samples_split=26;, score=0.828 total time=   2.4s
[CV 1/5] END max_depth=16, min_samples_leaf=12, min_samples_split=29;, score=0.813 total time=   2.5s
[CV 2/5] END max_depth=16, min_samples_leaf=12, min_samples_split=29;, score=0.828 total time=   2.5s
[CV 3/5] END max_depth=16, min_samples_leaf=12, min_samples_split=29;, score=0.827 total time=   2.2s
[CV 4/5] END max_depth=16, min_samples_leaf=12, min_samples_split=29;, score=0.843 total time=   2.3s
[CV 5/5] END max_depth=16, min_samples_leaf=12, min_samples_split=29;, score=0.824 total time=   2.3s
[CV 1/5] END max_depth=12, min_samples_leaf=5, min_samples_split=18;, score=0.826 total time=   2.4s
[CV 2/5] END max_depth=12, min_samples_leaf=5, min_samples_split=18;, score=0.843 total time=   2.5s
[CV 3/5] END max_depth=12, min_samples_leaf=5, min_samples_split=18;, score=0.849 total time=   2.4s
[CV 4/5] END max_depth=12, min_samples_leaf=5, min_samples_split=18;, score=0.855 total time=   2.5s
[CV 5/5] END max_depth=12, min_samples_leaf=5, min_samples_split=18;, score=0.839 total time=   2.5s
[CV 1/5] END max_depth=11, min_samples_leaf=12, min_samples_split=18;, score=0.812 total time=   2.1s
[CV 2/5] END max_depth=11, min_samples_leaf=12, min_samples_split=18;, score=0.827 total time=   2.2s
[CV 3/5] END max_depth=11, min_samples_leaf=12, min_samples_split=18;, score=0.827 total time=   2.1s
[CV 4/5] END max_depth=11, min_samples_leaf=12, min_samples_split=18;, score=0.841 total time=   2.3s
[CV 5/5] END max_depth=11, min_samples_leaf=12, min_samples_split=18;, score=0.824 total time=   2.1s
[CV 1/5] END max_depth=11, min_samples_leaf=10, min_samples_split=20;, score=0.818 total time=   2.2s
[CV 2/5] END max_depth=11, min_samples_leaf=10, min_samples_split=20;, score=0.832 total time=   2.3s
[CV 3/5] END max_depth=11, min_samples_leaf=10, min_samples_split=20;, score=0.835 total time=   2.2s
[CV 4/5] END max_depth=11, min_samples_leaf=10, min_samples_split=20;, score=0.846 total time=   2.5s
[CV 5/5] END max_depth=11, min_samples_leaf=10, min_samples_split=20;, score=0.832 total time=   2.3s
[CV 1/5] END max_depth=19, min_samples_leaf=8, min_samples_split=20;, score=0.826 total time=   2.8s
[CV 2/5] END max_depth=19, min_samples_leaf=8, min_samples_split=20;, score=0.842 total time=   2.9s
[CV 3/5] END max_depth=19, min_samples_leaf=8, min_samples_split=20;, score=0.845 total time=   2.8s
[CV 4/5] END max_depth=19, min_samples_leaf=8, min_samples_split=20;, score=0.857 total time=   3.1s
[CV 5/5] END max_depth=19, min_samples_leaf=8, min_samples_split=20;, score=0.838 total time=   3.1s
[CV 1/5] END max_depth=11, min_samples_leaf=14, min_samples_split=26;, score=0.810 total time=   2.7s
[CV 2/5] END max_depth=11, min_samples_leaf=14, min_samples_split=26;, score=0.822 total time=   2.7s
[CV 3/5] END max_depth=11, min_samples_leaf=14, min_samples_split=26;, score=0.824 total time=   2.7s
[CV 4/5] END max_depth=11, min_samples_leaf=14, min_samples_split=26;, score=0.837 total time=   2.8s
[CV 5/5] END max_depth=11, min_samples_leaf=14, min_samples_split=26;, score=0.821 total time=   2.7s
[CV 1/5] END max_depth=11, min_samples_leaf=14, min_samples_split=28;, score=0.810 total time=   2.7s
[CV 2/5] END max_depth=11, min_samples_leaf=14, min_samples_split=28;, score=0.822 total time=   2.7s
[CV 3/5] END max_depth=11, min_samples_leaf=14, min_samples_split=28;, score=0.824 total time=   2.7s
[CV 4/5] END max_depth=11, min_samples_leaf=14, min_samples_split=28;, score=0.837 total time=   2.8s
[CV 5/5] END max_depth=11, min_samples_leaf=14, min_samples_split=28;, score=0.821 total time=   2.7s
[CV 1/5] END max_depth=13, min_samples_leaf=12, min_samples_split=28;, score=0.814 total time=   2.8s
[CV 2/5] END max_depth=13, min_samples_leaf=12, min_samples_split=28;, score=0.828 total time=   2.9s
[CV 3/5] END max_depth=13, min_samples_leaf=12, min_samples_split=28;, score=0.827 total time=   2.7s
[CV 4/5] END max_depth=13, min_samples_leaf=12, min_samples_split=28;, score=0.842 total time=   2.9s
[CV 5/5] END max_depth=13, min_samples_leaf=12, min_samples_split=28;, score=0.825 total time=   3.0s
[CV 1/5] END max_depth=16, min_samples_leaf=13, min_samples_split=28;, score=0.813 total time=   2.3s
[CV 2/5] END max_depth=16, min_samples_leaf=13, min_samples_split=28;, score=0.829 total time=   2.3s
[CV 3/5] END max_depth=16, min_samples_leaf=13, min_samples_split=28;, score=0.826 total time=   2.2s
[CV 4/5] END max_depth=16, min_samples_leaf=13, min_samples_split=28;, score=0.842 total time=   2.2s
[CV 5/5] END max_depth=16, min_samples_leaf=13, min_samples_split=28;, score=0.825 total time=   2.2s
[CV 1/5] END max_depth=17, min_samples_leaf=9, min_samples_split=27;, score=0.819 total time=   2.3s
[CV 2/5] END max_depth=17, min_samples_leaf=9, min_samples_split=27;, score=0.831 total time=   2.3s
[CV 3/5] END max_depth=17, min_samples_leaf=9, min_samples_split=27;, score=0.837 total time=   2.2s
[CV 4/5] END max_depth=17, min_samples_leaf=9, min_samples_split=27;, score=0.850 total time=   2.4s
[CV 5/5] END max_depth=17, min_samples_leaf=9, min_samples_split=27;, score=0.830 total time=   2.3s
[CV 1/5] END max_depth=11, min_samples_leaf=9, min_samples_split=22;, score=0.817 total time=   2.2s
[CV 2/5] END max_depth=11, min_samples_leaf=9, min_samples_split=22;, score=0.827 total time=   2.6s
[CV 3/5] END max_depth=11, min_samples_leaf=9, min_samples_split=22;, score=0.837 total time=   2.6s
[CV 4/5] END max_depth=11, min_samples_leaf=9, min_samples_split=22;, score=0.847 total time=   2.6s
[CV 5/5] END max_depth=11, min_samples_leaf=9, min_samples_split=22;, score=0.830 total time=   2.4s
[CV 1/5] END max_depth=19, min_samples_leaf=13, min_samples_split=26;, score=0.816 total time=   2.2s
[CV 2/5] END max_depth=19, min_samples_leaf=13, min_samples_split=26;, score=0.831 total time=   2.3s
[CV 3/5] END max_depth=19, min_samples_leaf=13, min_samples_split=26;, score=0.826 total time=   2.1s
[CV 4/5] END max_depth=19, min_samples_leaf=13, min_samples_split=26;, score=0.844 total time=   2.3s
[CV 5/5] END max_depth=19, min_samples_leaf=13, min_samples_split=26;, score=0.828 total time=   2.2s
[CV 1/5] END max_depth=18, min_samples_leaf=5, min_samples_split=23;, score=0.827 total time=   2.5s
[CV 2/5] END max_depth=18, min_samples_leaf=5, min_samples_split=23;, score=0.847 total time=   2.5s
[CV 3/5] END max_depth=18, min_samples_leaf=5, min_samples_split=23;, score=0.848 total time=   2.5s
[CV 4/5] END max_depth=18, min_samples_leaf=5, min_samples_split=23;, score=0.858 total time=   2.6s
[CV 5/5] END max_depth=18, min_samples_leaf=5, min_samples_split=23;, score=0.839 total time=   2.6s
[CV 1/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.816 total time=   2.2s
[CV 2/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.831 total time=   2.3s
[CV 3/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.826 total time=   2.2s
[CV 4/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.844 total time=   2.3s
[CV 5/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.828 total time=   2.2s
[CV 1/5] END max_depth=10, min_samples_leaf=12, min_samples_split=22;, score=0.809 total time=   2.0s
[CV 2/5] END max_depth=10, min_samples_leaf=12, min_samples_split=22;, score=0.823 total time=   2.1s
[CV 3/5] END max_depth=10, min_samples_leaf=12, min_samples_split=22;, score=0.824 total time=   2.1s
[CV 4/5] END max_depth=10, min_samples_leaf=12, min_samples_split=22;, score=0.837 total time=   2.2s
[CV 5/5] END max_depth=10, min_samples_leaf=12, min_samples_split=22;, score=0.820 total time=   2.1s
[CV 1/5] END max_depth=12, min_samples_leaf=5, min_samples_split=22;, score=0.824 total time=   2.4s
[CV 2/5] END max_depth=12, min_samples_leaf=5, min_samples_split=22;, score=0.841 total time=   2.5s
[CV 3/5] END max_depth=12, min_samples_leaf=5, min_samples_split=22;, score=0.846 total time=   2.5s
[CV 4/5] END max_depth=12, min_samples_leaf=5, min_samples_split=22;, score=0.852 total time=   2.5s
[CV 5/5] END max_depth=12, min_samples_leaf=5, min_samples_split=22;, score=0.836 total time=   2.4s
[CV 1/5] END max_depth=12, min_samples_leaf=7, min_samples_split=15;, score=0.826 total time=   2.3s
[CV 2/5] END max_depth=12, min_samples_leaf=7, min_samples_split=15;, score=0.842 total time=   2.5s
[CV 3/5] END max_depth=12, min_samples_leaf=7, min_samples_split=15;, score=0.849 total time=   2.4s
[CV 4/5] END max_depth=12, min_samples_leaf=7, min_samples_split=15;, score=0.856 total time=   2.5s
[CV 5/5] END max_depth=12, min_samples_leaf=7, min_samples_split=15;, score=0.836 total time=   2.5s
[CV 1/5] END max_depth=14, min_samples_leaf=14, min_samples_split=21;, score=0.813 total time=   2.1s
[CV 2/5] END max_depth=14, min_samples_leaf=14, min_samples_split=21;, score=0.828 total time=   2.2s
[CV 3/5] END max_depth=14, min_samples_leaf=14, min_samples_split=21;, score=0.826 total time=   2.1s
[CV 4/5] END max_depth=14, min_samples_leaf=14, min_samples_split=21;, score=0.841 total time=   2.2s
[CV 5/5] END max_depth=14, min_samples_leaf=14, min_samples_split=21;, score=0.825 total time=   2.2s
[CV 1/5] END max_depth=19, min_samples_leaf=13, min_samples_split=26;, score=0.816 total time=   2.2s
[CV 2/5] END max_depth=19, min_samples_leaf=13, min_samples_split=26;, score=0.831 total time=   2.3s
[CV 3/5] END max_depth=19, min_samples_leaf=13, min_samples_split=26;, score=0.826 total time=   2.2s
[CV 4/5] END max_depth=19, min_samples_leaf=13, min_samples_split=26;, score=0.844 total time=   2.3s
[CV 5/5] END max_depth=19, min_samples_leaf=13, min_samples_split=26;, score=0.828 total time=   2.4s
[CV 1/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.816 total time=   2.3s
[CV 2/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.831 total time=   2.3s
[CV 3/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.826 total time=   2.3s
[CV 4/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.844 total time=   2.4s
[CV 5/5] END max_depth=16, min_samples_leaf=13, min_samples_split=22;, score=0.828 total time=   2.4s
[CV 1/5] END max_depth=11, min_samples_leaf=5, min_samples_split=21;, score=0.820 total time=   2.4s
[CV 2/5] END max_depth=11, min_samples_leaf=5, min_samples_split=21;, score=0.837 total time=   2.5s
[CV 3/5] END max_depth=11, min_samples_leaf=5, min_samples_split=21;, score=0.844 total time=   2.4s
[CV 4/5] END max_depth=11, min_samples_leaf=5, min_samples_split=21;, score=0.849 total time=   2.5s
[CV 5/5] END max_depth=11, min_samples_leaf=5, min_samples_split=21;, score=0.833 total time=   2.5s
[CV 1/5] END max_depth=16, min_samples_leaf=12, min_samples_split=19;, score=0.816 total time=   2.3s

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
                   estimator=RandomForestClassifier(max_features=None,
                                                    n_jobs=-1,
                                                    random_state=42),
                   n_iter=50,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000021C60B146E0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000021C2FDF79D0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000021C60A07D90>},
                   random_state=42, scoring='roc_auc', verbose=3)

In [7]:
pd.DataFrame(rnd_search.cv_results_)[['param_max_depth', 'param_min_samples_leaf', 'param_min_samples_split', 'mean_test_score']].sort_values(by='mean_test_score', ascending=False)

,param_max_depth,param_min_samples_leaf,param_min_samples_split,mean_test_score
42,14,7,15,0.845807
14,16,6,18,0.845792
30,18,5,23,0.843806
41,12,5,17,0.842985
9,18,5,25,0.842299
19,12,5,18,0.842247
3,17,9,18,0.842134
34,12,7,15,0.841852
5,15,9,16,0.841836
22,19,8,20,0.841636
2,19,7,21,0.841526
15,18,6,24,0.840643
7,14,5,26,0.840034
33,12,5,22,0.839575
1,17,9,21,0.839191
6,17,10,16,0.838994
11,16,8,23,0.838530
12,12,9,17,0.837812
10,19,7,26,0.837267
13,16,9,23,0.836863
38,11,5,21,0.836695
0,16,8,27,0.835236
48,14,11,21,0.834462
27,17,9,27,0.833346
8,19,10,27,0.832836
21,11,10,20,0.832511
47,13,8,28,0.832152
39,16,12,19,0.831863
4,17,12,17,0.831834
28,11,9,22,0.831626
46,12,11,15,0.831092
49,13,11,25,0.830861
17,11,8,26,0.829557
29,19,13,26,0.828952
36,19,13,26,0.828952
40,12,12,20,0.828818
31,16,13,22,0.828718
37,16,13,22,0.828718
25,13,12,28,0.827114
18,16,12,29,0.827010
16,18,14,19,0.827009
26,16,13,28,0.827005
45,19,14,26,0.827005
35,14,14,21,0.826519
43,14,14,21,0.826519
20,11,12,18,0.826473
44,16,13,29,0.825982
32,10,12,22,0.822803
23,11,14,26,0.822762
24,11,14,28,0.822762

In [8]:
print("Best params:", rnd_search.best_params_)
print("Best CV score:", rnd_search.best_score_)

best_model = rnd_search.best_estimator_

Best params: {'max_depth': 14, 'min_samples_leaf': 7, 'min_samples_split': 15}
Best CV score: 0.8458065677191972

In [12]:
y_pred = best_model.predict(X_train)
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.95      0.96      1933
           1       0.96      0.98      0.97      2060

    accuracy                           0.97      3993
   macro avg       0.97      0.97      0.97      3993
weighted avg       0.97      0.97      0.97      3993

#### Evaluación

In [13]:
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.75      0.76       484
           1       0.77      0.79      0.78       515

    accuracy                           0.77       999
   macro avg       0.77      0.77      0.77       999
weighted avg       0.77      0.77      0.77       999

#### Guardado

In [14]:
joblib.dump(best_model, f'./modelos_clasicos/modelos/ventanas/{dataset}/features_rf.pkl')

['./modelos_clasicos/modelos/ventanas/crudos/features_rf.pkl']